version: '2'
services:
  hah-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/hah/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hah
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
